### ISSUE TITLE
Max length pusher message?

### ISSUE THREAD

**Issue by wversluys** [jack9/pusherhub#2]
Hi,

I am obviously using this pusher library to create an app using the Corona sdk :). It seems to work fine so thanks a lot! There is however one issue I came across, whenever I tried to send a pusher message that was apparently too long it does not create the correct response.

The issue is in line 333:
```lua
msg = string.sub(self.buffer, payloadstart, payloadstart+payloadend)
```

Because when i use the following, everything seems to work fine:
```lua
msg = string.sub(self.buffer, payloadstart, string.len(self.buffer))
```

What was the reason for not using the full buffer string?

Regards,

Wouter

**Comment by jack9** [comment]
The short answer, is that I never finished correct calculations for continuation frames (messages over 126 bytes long). The code is wrong for calculating the payloadend for all cases, as far as I can tell. If you want to submit a patch for this, following these instructions, I will take it. If not, I will fix it as soon as I can.

See http://tools.ietf.org/html/rfc6455#section-5.2

    Decoding Payload Length

    To read the payload data, you must know when to stop reading. That's why the payload length is important to know. Unfortunately, this is somewhat complicated. To read it, follow these steps:

    Read bits 9-15 (inclusive) and interpret that as an unsigned integer. 
    - This is represented by lua variable - local payloadlen

    If it's 125 or less, then that's the length; you're done. 
    If it's 126
        Read the next 16 bits and interpret those as an unsigned integer. You're done.
    If it's 127
        Read the next 64 bits and interpret those as an unsigned integer. You're done.

The logic is here (corrected):

            opcode, payloadlen = self.parseHeader(string.sub(self.buffer,1,2)) -- first 2 bytes tell us everything about the following bits

            payloadstart = 3 -- bytes. no more metadata. the start and end are offset by 2 bytes
            payloadend = payloadlen+2 -- bytes. the start and end are offset by 2 bytes

            if payloadlen == 126 then -- we have 2 more bytes of metadata
                payloadstart = 5 -- starts on 5th byte. first 4 bytes of message are header data. 2 meta, 2 payload length description (16 bits)
                payloadend = self.bytesToDec(string.sub(self.buffer,3,4)) -- bytes. this is inclusive, 3 and 4 are converted
                payloadend = payloadend+2 -- bytes. offset by 2 more bytes
            elseif payloadlen == 127 then -- we have 8 more bytes of metadata
                payloadstart = 11 -- starts on 11th byte. first 10 bytes of message are header data. 2 meta, 8 payload length description (64 bits)
                payloadend = self.bytesToDec(string.sub(self.buffer,3,10)) -- this is inclusive, 3 through 10 are converted
                payloadend = payloadend+8 -- bytes. offset by 8 more bytes
            end

Per the standard:

        If 127, the following 8 bytes interpreted as a 64-bit unsigned integer (the most significant bit MUST be 0) are the payload length.

A message cannot exceed a maximum number of bytes: 
127 (7 bits) + 18,446,744,073,709,551,615 (64 bits) = 18,446,744,073,709,551,742 bytes 
and must have a correct count of the current payload so the receiver knows how many continuation frames will follow.

payloadend is supposed to be how many bytes long the message is.
The message starts at payloadstart (3rd byte or 5th byte or 11th byte, depending on payloadlen value)
and has to end somewhere. How do you calculate that? Well, you read from the extended payload data which varies based on each case. 
Add offset, which varies per case.

**Comment by jack9** [comment]
After some review, I've revised a number of lines, added some comments and changed how to calculate 
    local payloadend -- end of message byte number out of total bytes
See if the latest push helped. I do not have a test harness at this time.
